import type { Metadata } from 'next';
import '~/styles/globals.css';
import { Toaster } from '~/components/ui/toaster';
import { fontSans } from '~/fonts';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   console.log('fontSans', fontSans);

   return (
      <html lang="en">
         <head>
            <meta
               name="viewport"
               content="initial-scale=1, width=device-width"
            />
         </head>
         <body className={`${fontSans.variable} antialiased`}>
            <Toaster />
            <main>{children}</main>
         </body>
      </html>
   );
}
