import type { Metadata } from 'next';
import '~/styles/globals.css';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '~/components/themesProvider';
import { Toaster } from '~/components/ui/toaster';

const roboto = Roboto({
   subsets: ['latin'],
   variable: '--font-roboto',
   weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <head>
            <meta
               name="viewport"
               content="initial-scale=1, width=device-width"
            />
         </head>
         <body className={`${roboto.variable} antialiased`}>
            <Toaster />
            <main>{children}</main>
         </body>
      </html>
   );
}
